rplidar_node:
  ros__parameters:
    channel_type: serial
    serial_port: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
    serial_baudrate: 115200
    frame_id: laser_link
    inverted: false
    angle_compensate: true
    scan_mode: Sensitivity